/**
 * LAYERHUB BREED PERFORMANCE STANDARDS
 * Extracted directly from layer_standard_data.dart & dataset.json
 */

const LAYER_STANDARDS_DATA = [
  {
    "week": 16,
    "ageDays": 112,
    "phase": "Pre-Lay",
    "productionPercent": 0.0,
    "feedIntakeGrams": 80,
    "waterIntakeMl": 144.0,
    "eggWeightGrams": 0.0,
    "eggMassGrams": 0.0,
    "bodyWeightGrams": 1280,
    "feedConversion": null,
    "livabilityPercent": 99.97,
    "dailyMortalityPercent": 0.005,
    "cumulativeMortalityPercent": 0.04,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 0,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 0.0,
    "softOrRoughShellPercent": 0.0,
    "misshapenPercent": 0.0
  },
  {
    "week": 17,
    "ageDays": 119,
    "phase": "Pre-Lay",
    "productionPercent": 0.0,
    "feedIntakeGrams": 85,
    "waterIntakeMl": 153.0,
    "eggWeightGrams": 0.0,
    "eggMassGrams": 0.0,
    "bodyWeightGrams": 1340,
    "feedConversion": null,
    "livabilityPercent": 99.93,
    "dailyMortalityPercent": 0.005,
    "cumulativeMortalityPercent": 0.07,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 0,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 0.0,
    "softOrRoughShellPercent": 0.0,
    "misshapenPercent": 0.0
  },
  {
    "week": 18,
    "ageDays": 126,
    "phase": "Onset of Lay",
    "productionPercent": 5.0,
    "feedIntakeGrams": 90,
    "waterIntakeMl": 162.0,
    "eggWeightGrams": 42.0,
    "eggMassGrams": 2.1,
    "bodyWeightGrams": 1360,
    "feedConversion": 42.857,
    "livabilityPercent": 99.89,
    "dailyMortalityPercent": 0.005,
    "cumulativeMortalityPercent": 0.11,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 0,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.0,
    "softOrRoughShellPercent": 1.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 19,
    "ageDays": 133,
    "phase": "Onset of Lay",
    "productionPercent": 30.0,
    "feedIntakeGrams": 93,
    "waterIntakeMl": 167.4,
    "eggWeightGrams": 46.0,
    "eggMassGrams": 13.8,
    "bodyWeightGrams": 1390,
    "feedConversion": 6.739,
    "livabilityPercent": 99.79,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.21,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 2,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.17,
    "softOrRoughShellPercent": 1.17,
    "misshapenPercent": 0.5
  },
  {
    "week": 20,
    "ageDays": 140,
    "phase": "Onset of Lay",
    "productionPercent": 60.0,
    "feedIntakeGrams": 96,
    "waterIntakeMl": 172.8,
    "eggWeightGrams": 50.0,
    "eggMassGrams": 30.0,
    "bodyWeightGrams": 1420,
    "feedConversion": 3.2,
    "livabilityPercent": 99.69,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.32,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 6,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.33,
    "softOrRoughShellPercent": 0.83,
    "misshapenPercent": 0.5
  },
  {
    "week": 21,
    "ageDays": 147,
    "phase": "Onset of Lay",
    "productionPercent": 85.0,
    "feedIntakeGrams": 99,
    "waterIntakeMl": 178.2,
    "eggWeightGrams": 53.0,
    "eggMassGrams": 45.05,
    "bodyWeightGrams": 1450,
    "feedConversion": 2.198,
    "livabilityPercent": 99.58,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.42,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 12,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 22,
    "ageDays": 154,
    "phase": "Onset of Lay",
    "productionPercent": 92.0,
    "feedIntakeGrams": 102,
    "waterIntakeMl": 183.6,
    "eggWeightGrams": 55.0,
    "eggMassGrams": 50.6,
    "bodyWeightGrams": 1480,
    "feedConversion": 2.016,
    "livabilityPercent": 99.47,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.53,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 19,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 23,
    "ageDays": 161,
    "phase": "Peak Production",
    "productionPercent": 94.0,
    "feedIntakeGrams": 105,
    "waterIntakeMl": 189.0,
    "eggWeightGrams": 57.0,
    "eggMassGrams": 53.58,
    "bodyWeightGrams": 1510,
    "feedConversion": 1.96,
    "livabilityPercent": 99.37,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.63,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 25,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 24,
    "ageDays": 168,
    "phase": "Peak Production",
    "productionPercent": 95.0,
    "feedIntakeGrams": 108,
    "waterIntakeMl": 194.4,
    "eggWeightGrams": 58.0,
    "eggMassGrams": 55.1,
    "bodyWeightGrams": 1540,
    "feedConversion": 1.96,
    "livabilityPercent": 99.27,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.73,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 32,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 25,
    "ageDays": 175,
    "phase": "Peak Production",
    "productionPercent": 96.0,
    "feedIntakeGrams": 111,
    "waterIntakeMl": 199.8,
    "eggWeightGrams": 59.0,
    "eggMassGrams": 56.64,
    "bodyWeightGrams": 1570,
    "feedConversion": 1.96,
    "livabilityPercent": 99.16,
    "dailyMortalityPercent": 0.015,
    "cumulativeMortalityPercent": 0.84,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 38,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 26,
    "ageDays": 182,
    "phase": "Peak Production",
    "productionPercent": 95.9,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 59.4,
    "eggMassGrams": 56.96,
    "bodyWeightGrams": 1610,
    "feedConversion": 1.966,
    "livabilityPercent": 99.09,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 0.91,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 45,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 27,
    "ageDays": 189,
    "phase": "Peak Production",
    "productionPercent": 95.8,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 59.8,
    "eggMassGrams": 57.29,
    "bodyWeightGrams": 1620,
    "feedConversion": 1.955,
    "livabilityPercent": 99.02,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 0.98,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 52,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 28,
    "ageDays": 196,
    "phase": "Peak Production",
    "productionPercent": 95.7,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 60.2,
    "eggMassGrams": 57.61,
    "bodyWeightGrams": 1630,
    "feedConversion": 1.944,
    "livabilityPercent": 98.95,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.05,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 59,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 29,
    "ageDays": 203,
    "phase": "Peak Production",
    "productionPercent": 95.6,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 60.6,
    "eggMassGrams": 57.93,
    "bodyWeightGrams": 1640,
    "feedConversion": 1.933,
    "livabilityPercent": 98.88,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.12,
    "uniformityPercent": 90,
    "expectedEggsPerHen": 65,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 30,
    "ageDays": 210,
    "phase": "Peak Production",
    "productionPercent": 95.5,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.0,
    "eggMassGrams": 58.25,
    "bodyWeightGrams": 1650,
    "feedConversion": 1.923,
    "livabilityPercent": 98.81,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.19,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 72,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 31,
    "ageDays": 217,
    "phase": "Peak Production",
    "productionPercent": 95.3,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.1,
    "eggMassGrams": 58.31,
    "bodyWeightGrams": 1655,
    "feedConversion": 1.921,
    "livabilityPercent": 98.74,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.26,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 79,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.5,
    "softOrRoughShellPercent": 0.5,
    "misshapenPercent": 0.5
  },
  {
    "week": 32,
    "ageDays": 224,
    "phase": "Peak Production",
    "productionPercent": 95.2,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.3,
    "eggMassGrams": 58.36,
    "bodyWeightGrams": 1660,
    "feedConversion": 1.919,
    "livabilityPercent": 98.67,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.33,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 85,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.57,
    "softOrRoughShellPercent": 0.53,
    "misshapenPercent": 0.53
  },
  {
    "week": 33,
    "ageDays": 231,
    "phase": "Peak Production",
    "productionPercent": 95.0,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.5,
    "eggMassGrams": 58.41,
    "bodyWeightGrams": 1665,
    "feedConversion": 1.918,
    "livabilityPercent": 98.6,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.4,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 92,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.65,
    "softOrRoughShellPercent": 0.55,
    "misshapenPercent": 0.55
  },
  {
    "week": 34,
    "ageDays": 238,
    "phase": "Peak Production",
    "productionPercent": 94.9,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.6,
    "eggMassGrams": 58.46,
    "bodyWeightGrams": 1670,
    "feedConversion": 1.916,
    "livabilityPercent": 98.53,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.47,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 99,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.73,
    "softOrRoughShellPercent": 0.57,
    "misshapenPercent": 0.57
  },
  {
    "week": 35,
    "ageDays": 245,
    "phase": "Peak Production",
    "productionPercent": 94.8,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.8,
    "eggMassGrams": 58.51,
    "bodyWeightGrams": 1675,
    "feedConversion": 1.914,
    "livabilityPercent": 98.46,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.54,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 105,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.8,
    "softOrRoughShellPercent": 0.6,
    "misshapenPercent": 0.6
  },
  {
    "week": 36,
    "ageDays": 252,
    "phase": "Peak Production",
    "productionPercent": 94.6,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 61.9,
    "eggMassGrams": 58.56,
    "bodyWeightGrams": 1680,
    "feedConversion": 1.913,
    "livabilityPercent": 98.39,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.61,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 112,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.88,
    "softOrRoughShellPercent": 0.62,
    "misshapenPercent": 0.62
  },
  {
    "week": 37,
    "ageDays": 259,
    "phase": "Peak Production",
    "productionPercent": 94.5,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 62.0,
    "eggMassGrams": 58.61,
    "bodyWeightGrams": 1685,
    "feedConversion": 1.911,
    "livabilityPercent": 98.32,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.68,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 118,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 1.95,
    "softOrRoughShellPercent": 0.65,
    "misshapenPercent": 0.65
  },
  {
    "week": 38,
    "ageDays": 266,
    "phase": "Peak Production",
    "productionPercent": 94.3,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 62.2,
    "eggMassGrams": 58.65,
    "bodyWeightGrams": 1690,
    "feedConversion": 1.909,
    "livabilityPercent": 98.25,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.75,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 125,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.02,
    "softOrRoughShellPercent": 0.68,
    "misshapenPercent": 0.68
  },
  {
    "week": 39,
    "ageDays": 273,
    "phase": "Peak Production",
    "productionPercent": 94.2,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 62.4,
    "eggMassGrams": 58.7,
    "bodyWeightGrams": 1695,
    "feedConversion": 1.908,
    "livabilityPercent": 98.18,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.82,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 132,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.1,
    "softOrRoughShellPercent": 0.7,
    "misshapenPercent": 0.7
  },
  {
    "week": 40,
    "ageDays": 280,
    "phase": "Peak Production",
    "productionPercent": 94.0,
    "feedIntakeGrams": 112.0,
    "waterIntakeMl": 201.6,
    "eggWeightGrams": 62.5,
    "eggMassGrams": 58.75,
    "bodyWeightGrams": 1700,
    "feedConversion": 1.906,
    "livabilityPercent": 98.11,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.89,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 138,
    "shellQuality": "Excellent",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.17,
    "softOrRoughShellPercent": 0.72,
    "misshapenPercent": 0.72
  },
  {
    "week": 41,
    "ageDays": 287,
    "phase": "Mid Production",
    "productionPercent": 93.8,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.5,
    "eggMassGrams": 58.67,
    "bodyWeightGrams": 1702,
    "feedConversion": 1.926,
    "livabilityPercent": 98.04,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 1.96,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 145,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.25,
    "softOrRoughShellPercent": 0.75,
    "misshapenPercent": 0.75
  },
  {
    "week": 42,
    "ageDays": 294,
    "phase": "Mid Production",
    "productionPercent": 93.6,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.6,
    "eggMassGrams": 58.59,
    "bodyWeightGrams": 1704,
    "feedConversion": 1.929,
    "livabilityPercent": 97.97,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.03,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 151,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.33,
    "softOrRoughShellPercent": 0.78,
    "misshapenPercent": 0.78
  },
  {
    "week": 43,
    "ageDays": 301,
    "phase": "Mid Production",
    "productionPercent": 93.4,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.6,
    "eggMassGrams": 58.52,
    "bodyWeightGrams": 1706,
    "feedConversion": 1.931,
    "livabilityPercent": 97.9,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.1,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 158,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.4,
    "softOrRoughShellPercent": 0.8,
    "misshapenPercent": 0.8
  },
  {
    "week": 44,
    "ageDays": 308,
    "phase": "Mid Production",
    "productionPercent": 93.2,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.7,
    "eggMassGrams": 58.44,
    "bodyWeightGrams": 1708,
    "feedConversion": 1.934,
    "livabilityPercent": 97.83,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.17,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 164,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.48,
    "softOrRoughShellPercent": 0.82,
    "misshapenPercent": 0.82
  },
  {
    "week": 45,
    "ageDays": 315,
    "phase": "Mid Production",
    "productionPercent": 93.0,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.8,
    "eggMassGrams": 58.36,
    "bodyWeightGrams": 1710,
    "feedConversion": 1.936,
    "livabilityPercent": 97.76,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.24,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 171,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.55,
    "softOrRoughShellPercent": 0.85,
    "misshapenPercent": 0.85
  },
  {
    "week": 46,
    "ageDays": 322,
    "phase": "Mid Production",
    "productionPercent": 92.8,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.8,
    "eggMassGrams": 58.28,
    "bodyWeightGrams": 1712,
    "feedConversion": 1.939,
    "livabilityPercent": 97.69,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.31,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 177,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.62,
    "softOrRoughShellPercent": 0.88,
    "misshapenPercent": 0.88
  },
  {
    "week": 47,
    "ageDays": 329,
    "phase": "Mid Production",
    "productionPercent": 92.6,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.9,
    "eggMassGrams": 58.2,
    "bodyWeightGrams": 1714,
    "feedConversion": 1.942,
    "livabilityPercent": 97.62,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.38,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 184,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.7,
    "softOrRoughShellPercent": 0.9,
    "misshapenPercent": 0.9
  },
  {
    "week": 48,
    "ageDays": 336,
    "phase": "Mid Production",
    "productionPercent": 92.4,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 62.9,
    "eggMassGrams": 58.12,
    "bodyWeightGrams": 1716,
    "feedConversion": 1.944,
    "livabilityPercent": 97.55,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.45,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 190,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.77,
    "softOrRoughShellPercent": 0.93,
    "misshapenPercent": 0.93
  },
  {
    "week": 49,
    "ageDays": 343,
    "phase": "Mid Production",
    "productionPercent": 92.2,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.0,
    "eggMassGrams": 58.04,
    "bodyWeightGrams": 1718,
    "feedConversion": 1.947,
    "livabilityPercent": 97.48,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.52,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 197,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.85,
    "softOrRoughShellPercent": 0.95,
    "misshapenPercent": 0.95
  },
  {
    "week": 50,
    "ageDays": 350,
    "phase": "Mid Production",
    "productionPercent": 92.0,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.0,
    "eggMassGrams": 57.96,
    "bodyWeightGrams": 1720,
    "feedConversion": 1.95,
    "livabilityPercent": 97.41,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.59,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 203,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 2.92,
    "softOrRoughShellPercent": 0.97,
    "misshapenPercent": 0.97
  },
  {
    "week": 51,
    "ageDays": 357,
    "phase": "Mid Production",
    "productionPercent": 91.8,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.0,
    "eggMassGrams": 57.88,
    "bodyWeightGrams": 1722,
    "feedConversion": 1.952,
    "livabilityPercent": 97.34,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.66,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 210,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.0,
    "softOrRoughShellPercent": 1.0,
    "misshapenPercent": 1.0
  },
  {
    "week": 52,
    "ageDays": 364,
    "phase": "Mid Production",
    "productionPercent": 91.6,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.1,
    "eggMassGrams": 57.8,
    "bodyWeightGrams": 1724,
    "feedConversion": 1.955,
    "livabilityPercent": 97.27,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.73,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 216,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.1,
    "softOrRoughShellPercent": 1.05,
    "misshapenPercent": 1.05
  },
  {
    "week": 53,
    "ageDays": 371,
    "phase": "Mid Production",
    "productionPercent": 91.4,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.1,
    "eggMassGrams": 57.72,
    "bodyWeightGrams": 1726,
    "feedConversion": 1.958,
    "livabilityPercent": 97.2,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.8,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 223,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.2,
    "softOrRoughShellPercent": 1.1,
    "misshapenPercent": 1.1
  },
  {
    "week": 54,
    "ageDays": 378,
    "phase": "Mid Production",
    "productionPercent": 91.2,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.2,
    "eggMassGrams": 57.64,
    "bodyWeightGrams": 1728,
    "feedConversion": 1.96,
    "livabilityPercent": 97.13,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.87,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 229,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.3,
    "softOrRoughShellPercent": 1.15,
    "misshapenPercent": 1.15
  },
  {
    "week": 55,
    "ageDays": 385,
    "phase": "Mid Production",
    "productionPercent": 91.0,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.2,
    "eggMassGrams": 57.56,
    "bodyWeightGrams": 1730,
    "feedConversion": 1.963,
    "livabilityPercent": 97.06,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 2.94,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 235,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.4,
    "softOrRoughShellPercent": 1.2,
    "misshapenPercent": 1.2
  },
  {
    "week": 56,
    "ageDays": 392,
    "phase": "Mid Production",
    "productionPercent": 90.8,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.3,
    "eggMassGrams": 57.48,
    "bodyWeightGrams": 1732,
    "feedConversion": 1.966,
    "livabilityPercent": 96.99,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.01,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 242,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.5,
    "softOrRoughShellPercent": 1.25,
    "misshapenPercent": 1.25
  },
  {
    "week": 57,
    "ageDays": 399,
    "phase": "Mid Production",
    "productionPercent": 90.6,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.4,
    "eggMassGrams": 57.4,
    "bodyWeightGrams": 1734,
    "feedConversion": 1.969,
    "livabilityPercent": 96.92,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.08,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 248,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.6,
    "softOrRoughShellPercent": 1.3,
    "misshapenPercent": 1.3
  },
  {
    "week": 58,
    "ageDays": 406,
    "phase": "Mid Production",
    "productionPercent": 90.4,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.4,
    "eggMassGrams": 57.31,
    "bodyWeightGrams": 1736,
    "feedConversion": 1.972,
    "livabilityPercent": 96.85,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.15,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 254,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.7,
    "softOrRoughShellPercent": 1.35,
    "misshapenPercent": 1.35
  },
  {
    "week": 59,
    "ageDays": 413,
    "phase": "Mid Production",
    "productionPercent": 90.2,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.5,
    "eggMassGrams": 57.23,
    "bodyWeightGrams": 1738,
    "feedConversion": 1.974,
    "livabilityPercent": 96.78,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.22,
    "uniformityPercent": 88,
    "expectedEggsPerHen": 261,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.8,
    "softOrRoughShellPercent": 1.4,
    "misshapenPercent": 1.4
  },
  {
    "week": 60,
    "ageDays": 420,
    "phase": "Mid Production",
    "productionPercent": 90.0,
    "feedIntakeGrams": 113.0,
    "waterIntakeMl": 203.4,
    "eggWeightGrams": 63.5,
    "eggMassGrams": 57.15,
    "bodyWeightGrams": 1740,
    "feedConversion": 1.977,
    "livabilityPercent": 96.71,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.29,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 267,
    "shellQuality": "Very Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 3.9,
    "softOrRoughShellPercent": 1.45,
    "misshapenPercent": 1.45
  },
  {
    "week": 61,
    "ageDays": 427,
    "phase": "Late Production",
    "productionPercent": 89.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.5,
    "eggMassGrams": 57.02,
    "bodyWeightGrams": 1741,
    "feedConversion": 1.999,
    "livabilityPercent": 96.64,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.36,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 273,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.0,
    "softOrRoughShellPercent": 1.5,
    "misshapenPercent": 1.5
  },
  {
    "week": 62,
    "ageDays": 434,
    "phase": "Late Production",
    "productionPercent": 89.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.6,
    "eggMassGrams": 56.89,
    "bodyWeightGrams": 1742,
    "feedConversion": 2.004,
    "livabilityPercent": 96.57,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.43,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 279,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.1,
    "softOrRoughShellPercent": 1.55,
    "misshapenPercent": 1.55
  },
  {
    "week": 63,
    "ageDays": 441,
    "phase": "Late Production",
    "productionPercent": 89.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.6,
    "eggMassGrams": 56.75,
    "bodyWeightGrams": 1743,
    "feedConversion": 2.009,
    "livabilityPercent": 96.5,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.5,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 286,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.2,
    "softOrRoughShellPercent": 1.6,
    "misshapenPercent": 1.6
  },
  {
    "week": 64,
    "ageDays": 448,
    "phase": "Late Production",
    "productionPercent": 89.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.6,
    "eggMassGrams": 56.62,
    "bodyWeightGrams": 1744,
    "feedConversion": 2.013,
    "livabilityPercent": 96.43,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.57,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 292,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.3,
    "softOrRoughShellPercent": 1.65,
    "misshapenPercent": 1.65
  },
  {
    "week": 65,
    "ageDays": 455,
    "phase": "Late Production",
    "productionPercent": 88.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.6,
    "eggMassGrams": 56.49,
    "bodyWeightGrams": 1745,
    "feedConversion": 2.018,
    "livabilityPercent": 96.36,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.64,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 298,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.4,
    "softOrRoughShellPercent": 1.7,
    "misshapenPercent": 1.7
  },
  {
    "week": 66,
    "ageDays": 462,
    "phase": "Late Production",
    "productionPercent": 88.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.7,
    "eggMassGrams": 56.36,
    "bodyWeightGrams": 1746,
    "feedConversion": 2.023,
    "livabilityPercent": 96.29,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.71,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 304,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.5,
    "softOrRoughShellPercent": 1.75,
    "misshapenPercent": 1.75
  },
  {
    "week": 67,
    "ageDays": 469,
    "phase": "Late Production",
    "productionPercent": 88.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.7,
    "eggMassGrams": 56.22,
    "bodyWeightGrams": 1747,
    "feedConversion": 2.028,
    "livabilityPercent": 96.22,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.78,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 311,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.6,
    "softOrRoughShellPercent": 1.8,
    "misshapenPercent": 1.8
  },
  {
    "week": 68,
    "ageDays": 476,
    "phase": "Late Production",
    "productionPercent": 88.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.7,
    "eggMassGrams": 56.09,
    "bodyWeightGrams": 1748,
    "feedConversion": 2.032,
    "livabilityPercent": 96.15,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.85,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 317,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.7,
    "softOrRoughShellPercent": 1.85,
    "misshapenPercent": 1.85
  },
  {
    "week": 69,
    "ageDays": 483,
    "phase": "Late Production",
    "productionPercent": 87.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.8,
    "eggMassGrams": 55.96,
    "bodyWeightGrams": 1749,
    "feedConversion": 2.037,
    "livabilityPercent": 96.08,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.92,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 323,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.8,
    "softOrRoughShellPercent": 1.9,
    "misshapenPercent": 1.9
  },
  {
    "week": 70,
    "ageDays": 490,
    "phase": "Late Production",
    "productionPercent": 87.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.8,
    "eggMassGrams": 55.82,
    "bodyWeightGrams": 1750,
    "feedConversion": 2.042,
    "livabilityPercent": 96.01,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 3.99,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 329,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 4.9,
    "softOrRoughShellPercent": 1.95,
    "misshapenPercent": 1.95
  },
  {
    "week": 71,
    "ageDays": 497,
    "phase": "Late Production",
    "productionPercent": 87.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.8,
    "eggMassGrams": 55.69,
    "bodyWeightGrams": 1751,
    "feedConversion": 2.047,
    "livabilityPercent": 95.94,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.06,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 335,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.0,
    "softOrRoughShellPercent": 2.0,
    "misshapenPercent": 2.0
  },
  {
    "week": 72,
    "ageDays": 504,
    "phase": "Late Production",
    "productionPercent": 87.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.9,
    "eggMassGrams": 55.56,
    "bodyWeightGrams": 1752,
    "feedConversion": 2.052,
    "livabilityPercent": 95.87,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.13,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 341,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.15,
    "softOrRoughShellPercent": 2.08,
    "misshapenPercent": 2.05
  },
  {
    "week": 73,
    "ageDays": 511,
    "phase": "Late Production",
    "productionPercent": 86.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.9,
    "eggMassGrams": 55.42,
    "bodyWeightGrams": 1753,
    "feedConversion": 2.057,
    "livabilityPercent": 95.8,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.2,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 347,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.3,
    "softOrRoughShellPercent": 2.15,
    "misshapenPercent": 2.1
  },
  {
    "week": 74,
    "ageDays": 518,
    "phase": "Late Production",
    "productionPercent": 86.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 63.9,
    "eggMassGrams": 55.29,
    "bodyWeightGrams": 1754,
    "feedConversion": 2.062,
    "livabilityPercent": 95.73,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.27,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 353,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.45,
    "softOrRoughShellPercent": 2.23,
    "misshapenPercent": 2.15
  },
  {
    "week": 75,
    "ageDays": 525,
    "phase": "Late Production",
    "productionPercent": 86.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.0,
    "eggMassGrams": 55.16,
    "bodyWeightGrams": 1755,
    "feedConversion": 2.067,
    "livabilityPercent": 95.66,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.34,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 359,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.6,
    "softOrRoughShellPercent": 2.3,
    "misshapenPercent": 2.2
  },
  {
    "week": 76,
    "ageDays": 532,
    "phase": "Late Production",
    "productionPercent": 86.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.0,
    "eggMassGrams": 55.02,
    "bodyWeightGrams": 1756,
    "feedConversion": 2.072,
    "livabilityPercent": 95.59,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.41,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 365,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.75,
    "softOrRoughShellPercent": 2.38,
    "misshapenPercent": 2.25
  },
  {
    "week": 77,
    "ageDays": 539,
    "phase": "Late Production",
    "productionPercent": 85.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.0,
    "eggMassGrams": 54.89,
    "bodyWeightGrams": 1757,
    "feedConversion": 2.077,
    "livabilityPercent": 95.52,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.48,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 371,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 5.9,
    "softOrRoughShellPercent": 2.45,
    "misshapenPercent": 2.3
  },
  {
    "week": 78,
    "ageDays": 546,
    "phase": "Late Production",
    "productionPercent": 85.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.0,
    "eggMassGrams": 54.75,
    "bodyWeightGrams": 1758,
    "feedConversion": 2.082,
    "livabilityPercent": 95.45,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.55,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 377,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.05,
    "softOrRoughShellPercent": 2.52,
    "misshapenPercent": 2.35
  },
  {
    "week": 79,
    "ageDays": 553,
    "phase": "Late Production",
    "productionPercent": 85.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.1,
    "eggMassGrams": 54.62,
    "bodyWeightGrams": 1759,
    "feedConversion": 2.087,
    "livabilityPercent": 95.38,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.62,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 383,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.2,
    "softOrRoughShellPercent": 2.6,
    "misshapenPercent": 2.4
  },
  {
    "week": 80,
    "ageDays": 560,
    "phase": "Late Production",
    "productionPercent": 85.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.1,
    "eggMassGrams": 54.48,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.092,
    "livabilityPercent": 95.31,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.69,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 389,
    "shellQuality": "Good",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.35,
    "softOrRoughShellPercent": 2.67,
    "misshapenPercent": 2.45
  },
  {
    "week": 81,
    "ageDays": 567,
    "phase": "End of Cycle",
    "productionPercent": 84.7,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.1,
    "eggMassGrams": 54.31,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.099,
    "livabilityPercent": 95.24,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.76,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 395,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.5,
    "softOrRoughShellPercent": 2.75,
    "misshapenPercent": 2.5
  },
  {
    "week": 82,
    "ageDays": 574,
    "phase": "End of Cycle",
    "productionPercent": 84.4,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.1,
    "eggMassGrams": 54.13,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.106,
    "livabilityPercent": 95.17,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.83,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 401,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.65,
    "softOrRoughShellPercent": 2.83,
    "misshapenPercent": 2.55
  },
  {
    "week": 83,
    "ageDays": 581,
    "phase": "End of Cycle",
    "productionPercent": 84.1,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.2,
    "eggMassGrams": 53.96,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.113,
    "livabilityPercent": 95.1,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.9,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 407,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.8,
    "softOrRoughShellPercent": 2.9,
    "misshapenPercent": 2.6
  },
  {
    "week": 84,
    "ageDays": 588,
    "phase": "End of Cycle",
    "productionPercent": 83.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.2,
    "eggMassGrams": 53.78,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.12,
    "livabilityPercent": 95.03,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 4.97,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 413,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 6.95,
    "softOrRoughShellPercent": 2.98,
    "misshapenPercent": 2.65
  },
  {
    "week": 85,
    "ageDays": 595,
    "phase": "End of Cycle",
    "productionPercent": 83.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.2,
    "eggMassGrams": 53.61,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.127,
    "livabilityPercent": 94.96,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.04,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 419,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 7.1,
    "softOrRoughShellPercent": 3.05,
    "misshapenPercent": 2.7
  },
  {
    "week": 86,
    "ageDays": 602,
    "phase": "End of Cycle",
    "productionPercent": 83.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.2,
    "eggMassGrams": 53.43,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.134,
    "livabilityPercent": 94.89,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.11,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 425,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 7.25,
    "softOrRoughShellPercent": 3.12,
    "misshapenPercent": 2.75
  },
  {
    "week": 87,
    "ageDays": 609,
    "phase": "End of Cycle",
    "productionPercent": 82.9,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.2,
    "eggMassGrams": 53.25,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.141,
    "livabilityPercent": 94.82,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.18,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 430,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 7.4,
    "softOrRoughShellPercent": 3.2,
    "misshapenPercent": 2.8
  },
  {
    "week": 88,
    "ageDays": 616,
    "phase": "End of Cycle",
    "productionPercent": 82.6,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.3,
    "eggMassGrams": 53.08,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.148,
    "livabilityPercent": 94.75,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.25,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 436,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 7.55,
    "softOrRoughShellPercent": 3.27,
    "misshapenPercent": 2.85
  },
  {
    "week": 89,
    "ageDays": 623,
    "phase": "End of Cycle",
    "productionPercent": 82.3,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.3,
    "eggMassGrams": 52.9,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.155,
    "livabilityPercent": 94.68,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.32,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 442,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 7.7,
    "softOrRoughShellPercent": 3.35,
    "misshapenPercent": 2.9
  },
  {
    "week": 90,
    "ageDays": 630,
    "phase": "End of Cycle",
    "productionPercent": 82.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.3,
    "eggMassGrams": 52.73,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.162,
    "livabilityPercent": 94.61,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.39,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 448,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 7.85,
    "softOrRoughShellPercent": 3.42,
    "misshapenPercent": 2.95
  },
  {
    "week": 91,
    "ageDays": 637,
    "phase": "End of Cycle",
    "productionPercent": 81.7,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.3,
    "eggMassGrams": 52.55,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.169,
    "livabilityPercent": 94.54,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.46,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 453,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 92,
    "ageDays": 644,
    "phase": "End of Cycle",
    "productionPercent": 81.4,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.3,
    "eggMassGrams": 52.37,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.177,
    "livabilityPercent": 94.47,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.53,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 459,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 93,
    "ageDays": 651,
    "phase": "End of Cycle",
    "productionPercent": 81.1,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.4,
    "eggMassGrams": 52.2,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.184,
    "livabilityPercent": 94.4,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.6,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 465,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 94,
    "ageDays": 658,
    "phase": "End of Cycle",
    "productionPercent": 80.8,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.4,
    "eggMassGrams": 52.02,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.192,
    "livabilityPercent": 94.33,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.67,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 470,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 95,
    "ageDays": 665,
    "phase": "End of Cycle",
    "productionPercent": 80.5,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.4,
    "eggMassGrams": 51.84,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.199,
    "livabilityPercent": 94.26,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.74,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 476,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 96,
    "ageDays": 672,
    "phase": "End of Cycle",
    "productionPercent": 80.2,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.4,
    "eggMassGrams": 51.66,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.207,
    "livabilityPercent": 94.19,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.81,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 482,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 97,
    "ageDays": 679,
    "phase": "End of Cycle",
    "productionPercent": 79.9,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.4,
    "eggMassGrams": 51.49,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.214,
    "livabilityPercent": 94.12,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.88,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 487,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 98,
    "ageDays": 686,
    "phase": "End of Cycle",
    "productionPercent": 79.6,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.5,
    "eggMassGrams": 51.31,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.222,
    "livabilityPercent": 94.05,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 5.95,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 493,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 99,
    "ageDays": 693,
    "phase": "End of Cycle",
    "productionPercent": 79.3,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.5,
    "eggMassGrams": 51.13,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.229,
    "livabilityPercent": 93.98,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 6.02,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 498,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  },
  {
    "week": 100,
    "ageDays": 700,
    "phase": "End of Cycle",
    "productionPercent": 79.0,
    "feedIntakeGrams": 114.0,
    "waterIntakeMl": 205.2,
    "eggWeightGrams": 64.5,
    "eggMassGrams": 50.96,
    "bodyWeightGrams": 1760,
    "feedConversion": 2.237,
    "livabilityPercent": 93.91,
    "dailyMortalityPercent": 0.01,
    "cumulativeMortalityPercent": 6.09,
    "uniformityPercent": 85,
    "expectedEggsPerHen": 504,
    "shellQuality": "Fair",
    "performanceGrade": "Target",
    "acceptableBreakagePercent": 8.0,
    "softOrRoughShellPercent": 3.5,
    "misshapenPercent": 3.0
  }
];

// Map of week -> standard record
const LAYER_STANDARDS_MAP = {};
LAYER_STANDARDS_DATA.forEach(s => {
  LAYER_STANDARDS_MAP[s.week] = s;
});

/**
 * Get standard performance benchmark record for a given flock age in weeks
 */
function getBreedStandardForWeek(week) {
  if (LAYER_STANDARDS_MAP[week]) {
    return LAYER_STANDARDS_MAP[week];
  }
  if (week < 16) return LAYER_STANDARDS_DATA[0];
  if (week > 100) return LAYER_STANDARDS_DATA[LAYER_STANDARDS_DATA.length - 1];
  return LAYER_STANDARDS_DATA[LAYER_STANDARDS_DATA.length - 1];
}
